### ISSUE TITLE
Bug in rref computation

### ISSUE THREAD

**Issue by ClemensHofstadler** [munuxi/sparse_rref#1]
The following minimal example yields a wrong rref:
2 3 R
1 1 1
1 3 1
2 1 1
2 2 -1
0 0 0

This is the output that I get:

These are the (wrong) pivots:
2, 2
1, 3

and this is the (wrong) rref:
%%MatrixMarket matrix coordinate rational general
2 3 4
1 1 1
1 3 1
2 1 -1
2 2 1

Could you please have a look at that and fix it? Thank you!

**Comment by munuxi** [comment]
Hi, it is not wrong. The code is designed compute RREF with row and column permutation as explained in README, which hugely speeds up the algorithm. The row and column permutation are implicitly given by pivots. In your example, the result is the 2*3 matrix [[1 0 1], [-1 1 0]], and in the permutation given by the chosen pivots (2,2), (1,3), we can first we take the submatrix involving rows 2,1 and columns 2,3, that is [[1 0], [0 1]]. 

This example can also show why it will be more efficient to take some row and column permutations. The original matrix is [[1 0 1], [1 -1 0]], the RREF without permutations needs to compute [1 -1 0] - [1 0 1], but with permutations, the code first looks for a submatrix that is already upper triangular after permutations, and then it only needs to compute (-1)*[1 -1 0].

**Comment by ClemensHofstadler** [comment]
Thank you for the fast reply!

I see. I misread the part with the column permutations in the README. Sorry. But now it is clear. Thank you for clarifying! 

Is it possible to use your code without the column permutations? Because my application requires me to keep the order of the columns fixed.

**Comment by munuxi** [comment]
Thank you for trying my code. However, it is not supported now since 1. some libraries or softwires have already supported it (RREF, LU or PLU) well (LinBox, Sage, Flint...) 2. the algorithm without column permutations would not get the similar efficiency in some cases. 

I understand that the order of columns is important in some applications, and I am still thinking how to implement it since most of optimization in my code will not take effect now...
